
# Use FUNCTION_HOST localhost:14142 or 

# Local
# @host = http://localhost:14142
# Function
# @host = https://hwi-products.azurewebsites.net
# APIM Endpoint
@host = https://hello-world-industries.azure-api.net
### 

GET {{host}}/api/products/
Ocp-Apim-Subscription-Key: {{subscription_key}}

###

GET {{host}}/api/products/5
Ocp-Apim-Subscription-Key: {{subscription_key}}

###

POST {{host}}/api/products
Ocp-Apim-Subscription-Key: {{subscription_key}}
content-type: application/json

{
    "productId": 191,
    "manufacturer": "Hello World Industries",
    "sku": "1bd6a2c9-ef6b-51a7-8932-1bc5b0dcee6c",
    "upc": "5674127452",
    "pricePerUnit": "249.99",
    "quantityOnHand": 1,
    "productName": "Fancy Keyboard"
}

###

GET {{host}}/api/products/192
Ocp-Apim-Subscription-Key: {{subscription_key}}

###

DELETE {{host}}/api/products/191
Ocp-Apim-Subscription-Key: {{subscription_key}}

