
# Use FUNCTION_HOST localhost:14142 or 

@host = http://localhost:14142
# @host = https://hwi-products.azurewebsites.net

### 

GET {{host}}/api/products/

###

GET {{host}}/api/products/5

###

POST {{host}}/api/products
content-type: application/json

{
    "productId": 191,
    "manufacturer": "Hello World Industries",
    "sku": "1bd6a2c9-ef6b-51a7-8932-1bc5b0dcee6c",
    "upc": "5674127452",
    "pricePerUnit": "249.99",
    "quantityOnHand": 1,
    "productName": "Fancy Keyboard"
}

###

GET {{host}}/api/products/191

###

DELETE {{host}}/api/products/191

